version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: jakarta.servlet:jakarta.servlet-api
      - dependency-name: org.infinispan:infinispan-bom
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: org.jgroups:jgroups
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "maven"
    directory: "/session/spec/servlet/4.0"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: jakarta.servlet:jakarta.servlet-api
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "maven"
    directory: "/session/spec/servlet/5.0"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: jakarta.servlet:jakarta.servlet-api
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "maven"
    directory: "/session/spec/servlet/6.0"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: jakarta.servlet:jakarta.servlet-api
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "maven"
    directory: "/session/spec/servlet/6.1"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: jakarta.servlet:jakarta.servlet-api
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
